### ISSUE TITLE
资源获取咨询

### ISSUE THREAD

**Issue by hyddd** [RaphaelHong/WirelessMeasurePlatform#2]
您好，我看到您项目中用到了POLAQLIB，里面的PolqaLicenseFile.txt可否发一份与我，我最近在研究POLQA相关，非常感谢~hydddchen@gmail.com

**Comment by RaphaelHong** [comment]
抱歉啊，这是我以前的一个大项目，POLAQ部分的东西掌握在我的BOSS手里，源工程里边也没有这个文件。
